package ru.tsconsulting.vtb24.soa.son.prov.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-30T23:57:26.970+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://v1.prov.son.soa.vtb24.tsconsulting.ru/", name = "SendingMessageService")
@XmlSeeAlso({com.oracle.xmlns.enterpriseobjects.core.common.v2.ObjectFactory.class, ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.ObjectFactory.class, ObjectFactory.class, com.oracle.xmlns.utilitycomposites.sonprovtav1.asynccorrelationhelper.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, ru.tsconsulting.vtb24.soa.son.prov.v1.types.ObjectFactory.class, ru.vtb24.schemas.shared.interaction.ObjectFactory.class, com.oracle.xmlns.enterpriseobjects.core.custom.common.v2.ObjectFactory.class, oasis.names.tc.xacml._2_0.context.schema.cd._04.ObjectFactory.class, oasis.names.tc.xacml._2_0.policy.schema.cd._04.ObjectFactory.class})
public interface SendingMessageService {

    @WebMethod
    @RequestWrapper(localName = "sendSyncMessage", targetNamespace = "http://v1.prov.son.soa.vtb24.tsconsulting.ru/", className = "ru.tsconsulting.vtb24.soa.son.prov.v1.SendSyncMessage")
    @ResponseWrapper(localName = "sendSyncMessageResponse", targetNamespace = "http://v1.prov.son.soa.vtb24.tsconsulting.ru/", className = "ru.tsconsulting.vtb24.soa.son.prov.v1.SendSyncMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.tsconsulting.vtb24.soa.son.prov.v1.types.ResponseParameters sendSyncMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.tsconsulting.vtb24.soa.son.prov.v1.types.RequestParameters arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sendAsyncMessage", targetNamespace = "http://v1.prov.son.soa.vtb24.tsconsulting.ru/", className = "ru.tsconsulting.vtb24.soa.son.prov.v1.SendAsyncMessage")
    @ResponseWrapper(localName = "sendAsyncMessageResponse", targetNamespace = "http://v1.prov.son.soa.vtb24.tsconsulting.ru/", className = "ru.tsconsulting.vtb24.soa.son.prov.v1.SendAsyncMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sendAsyncMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.tsconsulting.vtb24.soa.son.prov.v1.types.RequestParameters arg0
    );
}
