
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ru.tsconsulting.vtb24.soa.son.prov.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-30T23:57:26.905+03:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "$service.ServiceName",
                      targetNamespace = "$service.Namespace",
                      wsdlLocation = "file:/C:/Users/User/IdeaProjects/spring/boot/demo/src/main/resources/son/SONProvTAWrapper1.wsdl",
                      endpointInterface = "ru.tsconsulting.vtb24.soa.son.prov.v1.SendingMessageService")
                      
public class SendingMessageServiceImpl implements SendingMessageService {

    private static final Logger LOG = Logger.getLogger(SendingMessageServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ru.tsconsulting.vtb24.soa.son.prov.v1.SendingMessageService#sendSyncMessage(ru.tsconsulting.vtb24.soa.son.prov.v1.types.RequestParameters arg0)*
     */
    public ru.tsconsulting.vtb24.soa.son.prov.v1.types.ResponseParameters sendSyncMessage(ru.tsconsulting.vtb24.soa.son.prov.v1.types.RequestParameters arg0) { 
        LOG.info("Executing operation sendSyncMessage");
        System.out.println(arg0);
        try {
            ru.tsconsulting.vtb24.soa.son.prov.v1.types.ResponseParameters _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.tsconsulting.vtb24.soa.son.prov.v1.SendingMessageService#sendAsyncMessage(ru.tsconsulting.vtb24.soa.son.prov.v1.types.RequestParameters arg0)*
     */
    public java.lang.String sendAsyncMessage(ru.tsconsulting.vtb24.soa.son.prov.v1.types.RequestParameters arg0) { 
        LOG.info("Executing operation sendAsyncMessage");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
