
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-30T23:57:26.953+03:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "$service.ServiceName",
                      targetNamespace = "$service.Namespace",
                      wsdlLocation = "file:/C:/Users/User/IdeaProjects/spring/boot/demo/src/main/resources/son/SONProvTAWrapper1.wsdl",
                      endpointInterface = "ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.AsyncSONProvTARequest")
                      
public class AsyncSONProvTAImpl implements AsyncSONProvTARequest {

    private static final Logger LOG = Logger.getLogger(AsyncSONProvTAImpl.class.getName());

    /* (non-Javadoc)
     * @see ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.AsyncSONProvTA#asyncSONRequest(ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SONReqMsgType asyncSONRequestEBM)*
     */
    public void asyncSONRequest(SONReqMsgType asyncSONRequestEBM) { 
        LOG.info("Executing operation asyncSONRequest");
        System.out.println(asyncSONRequestEBM);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
