
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-10-07T14:47:51.441+03:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SONProvTAService",
                      portName = "SONProvTA_Port_sync",
                      targetNamespace = "http://www.vtb24.ru/ApplicationConnectorServiceLibrary/SON/Providers/SONProvTA/V1",
                      wsdlLocation = "file:/C:/Users/User/IdeaProjects/spring/boot/demo/src/main/resources/son/SONProvTAWrapper1.wsdl",
                      endpointInterface = "ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SyncSONProvTA")
                      
public class SONProvTA_Port_SyncImpl implements SyncSONProvTA {

    private static final Logger LOG = Logger.getLogger(SONProvTA_Port_SyncImpl.class.getName());

    /* (non-Javadoc)
     * @see ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SyncSONProvTA#syncSONRequest(ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SONReqMsgType sonRequestEBM)*
     */
    public ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SONRespMsgType syncSONRequest(SONReqMsgType sonRequestEBM) throws CommonFaultMessage   { 
        LOG.info("Executing operation syncSONRequest");
        System.out.println(sonRequestEBM);
        try {
            ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SONRespMsgType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CommonFaultMessage("CommonFaultMessage...");
    }

}
