
package ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-10-07T14:47:51.410+03:00
 * Generated source version: 3.2.1
 * 
 */
public final class SyncSONProvTA_SONProvTAPortSync_Client {

    private static final QName SERVICE_NAME = new QName("http://www.vtb24.ru/ApplicationConnectorServiceLibrary/SON/Providers/SONProvTA/V1", "SONProvTAService");

    private SyncSONProvTA_SONProvTAPortSync_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SONProvTAService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SONProvTAService ss = new SONProvTAService(wsdlURL, SERVICE_NAME);
        SyncSONProvTA port = ss.getSONProvTAPortSync();  
        
        {
        System.out.println("Invoking syncSONRequest...");
        ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SONReqMsgType _syncSONRequest_sonRequestEBM = null;
        try {
            ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.SONRespMsgType _syncSONRequest__return = port.syncSONRequest(_syncSONRequest_sonRequestEBM);
            System.out.println("syncSONRequest.result=" + _syncSONRequest__return);

        } catch (CommonFaultMessage e) { 
            System.out.println("Expected exception: CommonFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
