package com.oracle.sca.soapservice.utilitycomposites.sonprovtav1.asyncmsgrespservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-30T23:57:27.002+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://oracle.com/sca/soapservice/UtilityComposites/SONProvTAV1/AsyncMsgRespService", name = "execute_ptt")
@XmlSeeAlso({com.oracle.xmlns.enterpriseobjects.core.common.v2.ObjectFactory.class, ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.ObjectFactory.class, ru.tsconsulting.vtb24.soa.son.prov.v1.ObjectFactory.class, com.oracle.xmlns.utilitycomposites.sonprovtav1.asynccorrelationhelper.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, ru.tsconsulting.vtb24.soa.son.prov.v1.types.ObjectFactory.class, ru.vtb24.schemas.shared.interaction.ObjectFactory.class, com.oracle.xmlns.enterpriseobjects.core.custom.common.v2.ObjectFactory.class, oasis.names.tc.xacml._2_0.context.schema.cd._04.ObjectFactory.class, oasis.names.tc.xacml._2_0.policy.schema.cd._04.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ExecutePtt {

    @WebMethod
    @Oneway
    public void execute(
        @WebParam(partName = "part", name = "Response", targetNamespace = "urn:www.vtb24.ru:schemas:shared:interaction")
        ru.vtb24.schemas.shared.interaction.ResponseBaseType part
    );
}
