
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.oracle.sca.soapservice.utilitycomposites.sonprovtav1.asyncmsgrespservice;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-30T23:57:26.962+03:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "$service.ServiceName",
                      targetNamespace = "$service.Namespace",
                      wsdlLocation = "file:/C:/Users/User/IdeaProjects/spring/boot/demo/src/main/resources/son/SONProvTAWrapper1.wsdl",
                      endpointInterface = "com.oracle.sca.soapservice.utilitycomposites.sonprovtav1.asyncmsgrespservice.ExecutePtt")
                      
public class ExecutePttImpl implements ExecutePtt {

    private static final Logger LOG = Logger.getLogger(ExecutePttImpl.class.getName());

    /* (non-Javadoc)
     * @see com.oracle.sca.soapservice.utilitycomposites.sonprovtav1.asyncmsgrespservice.ExecutePtt#execute(ru.vtb24.schemas.shared.interaction.ResponseBaseType part)*
     */
    public void execute(ru.vtb24.schemas.shared.interaction.ResponseBaseType part) { 
        LOG.info("Executing operation execute");
        System.out.println(part);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
