package com.oracle.xmlns.utilitycomposites.sonprovtav1.asynccorrelationhelper;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-30T23:57:26.977+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/UtilityComposites/SONProvTAV1/AsyncCorrelationHelper", name = "AsyncCorrelationHelper")
@XmlSeeAlso({com.oracle.xmlns.enterpriseobjects.core.common.v2.ObjectFactory.class, ru.vtb24.applicationconnectorservicelibrary.son.providers.sonprovta.v1.ObjectFactory.class, ru.tsconsulting.vtb24.soa.son.prov.v1.ObjectFactory.class, ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, ru.tsconsulting.vtb24.soa.son.prov.v1.types.ObjectFactory.class, ru.vtb24.schemas.shared.interaction.ObjectFactory.class, com.oracle.xmlns.enterpriseobjects.core.custom.common.v2.ObjectFactory.class, oasis.names.tc.xacml._2_0.context.schema.cd._04.ObjectFactory.class, oasis.names.tc.xacml._2_0.policy.schema.cd._04.ObjectFactory.class})
public interface AsyncCorrelationHelper {

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/UtilityComposites/SONProvTAV1/AsyncCorrelationHelper", className = "com.oracle.xmlns.utilitycomposites.sonprovtav1.asynccorrelationhelper.Process")
    public void process(
        @WebParam(name = "input", targetNamespace = "http://xmlns.oracle.com/UtilityComposites/SONProvTAV1/AsyncCorrelationHelper")
        java.lang.String input
    );
}
